config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :total_rewards, only: :index do
      collection do
        get 'download'
      end
    end

    resources :users do
      member do
        get 'impersonate'
      end
    end
    resources :assessment_rounds

    root to: "users#index"
  end

  resources :user_assessments, only: [:index]
  resources :assessment_rounds, only: [:new, :create, :show, :edit, :update] do
    resources :assessments, only: [:index, :new, :create] do
      collection do
        get 'table_view'
        get 'box_review'
        post 'update_box_view'
      end
    end

    member do
      get 'closed_view'
      get 'review'
      get 'download'
      post 'toggle_review_state'
      post 'close'
      post 'sync'
    end
  end

  devise_for :users, controllers: {
    confirmations: 'confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'
  get '/about', to: 'home#about'
  get '/dashboard', to: 'dashboard#index'
end

app/models/assessment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: assessments
#
#  id                    :bigint           not null, primary key
#  confirmed_at          :datetime
#  emergency_contact     :string
#  given_by              :integer
#  motivation            :text
#  note                  :text
#  score_performance     :integer
#  score_potential       :integer
#  synced_at             :datetime
#  time_frame            :string
#  time_frame_promotion  :string
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  assessment_round_id   :bigint           not null
#  team_member_bamboo_id :integer
#
# Indexes
#
#  index_assessments_on_assessment_round_id  (assessment_round_id)
#
# Foreign Keys
#
#  fk_rails_...  (assessment_round_id => assessment_rounds.id)
#
class Assessment < ApplicationRecord
  belongs_to :user, foreign_key: 'given_by', inverse_of: :assessments
  belongs_to :assessment_round

  validates :given_by, presence: true
  validates :team_member_bamboo_id, presence: true

  PERFORMANCE_VALUES = [:developing, :performing, :exceeding].freeze
  POTENTIAL_VALUES = [:low, :medium, :high].freeze

  enum score_performance: PERFORMANCE_VALUES
  enum score_potential: POTENTIAL_VALUES

  scope :confirmed, -> { where.not(confirmed_at: nil) }
  scope :most_recent, -> { select('DISTINCT ON (team_member_bamboo_id) *').order("team_member_bamboo_id, created_at DESC") }

  # Returns the most recent assessments given to every report
  def self.most_recent_in_round_for(reports, round)
    select('DISTINCT ON (team_member_bamboo_id) *').where(assessment_round: round).where(team_member_bamboo_id: reports.pluck('id')).order("team_member_bamboo_id, created_at DESC")
  end

  def self.most_recent_in_round(round)
    select('DISTINCT ON (team_member_bamboo_id) *').where(assessment_round: round).order("team_member_bamboo_id, created_at DESC")
  end
end

app/controllers/assessments_controller.rb
# frozen_string_literal: true

class AssessmentsController < ApplicationController
  before_action :set_open_assessment_rounds
  before_action :set_assessment_round, only: [:index, :box_review, :table_view]

  # GET /assessments
  # GET /assessments.json
  def index
    @reports, @assessments = AssessmentPolicy::Scope.new(current_user, Assessment).resolve_for_round(@assessment_round)
    @reports.each { |report| report['fullName1'] = Faker::Name.name } if params[:demo] || ENV['DEMO_DATA']
    authorize current_user, policy_class: AssessmentPolicy
  end

  def box_review
    @reports, @assessments = AssessmentPolicy::Scope.new(current_user, Assessment).resolve_for_people_business_partner(@assessment_round)
    @reports.each { |report| report['fullName1'] = Faker::Name.name } if params[:demo] || ENV['DEMO_DATA']
    @assessments = @assessments.reject { |assessment| params[:excluded_team_members]&.map(&:to_i)&.include? assessment.team_member_bamboo_id }
    @excluded_team_members = params.fetch(:excluded_team_members, [])

    authorize @assessment_round
  end

  def table_view
    @reports, @assessments = AssessmentPolicy::Scope.new(current_user, Assessment).resolve_for_round(@assessment_round)
    @reports.each { |report| report['fullName1'] = Faker::Name.name } if params[:demo] || ENV['DEMO_DATA']
    @reports.select! { |report| Date.parse(report['hireDate']).before?(@assessment_round.cut_off) } if @assessment_round.cut_off

    @confirmed_assessments = @assessments.where.not(confirmed_at: nil)
    authorize current_user, policy_class: AssessmentPolicy
  end

  def update_box_view
    assessment_round = @open_assessment_rounds.find(params['assessmentRound'])

    params[:reports].each do |report|
      next if report['emergencyContact'].nil? && (report['performance'].nil? || report['performance'] == 0) # rubocop:disable Style/NumericPredicate

      @assessment = current_user.assessments.new(
        score_performance: report['performance'],
        score_potential: report['potential'],
        team_member_bamboo_id: report['id'].to_i,
        assessment_round: assessment_round,
        emergency_contact: report['emergencyContact'],
        time_frame: report['readyWhen'],
        time_frame_promotion: report['readyForPromotion'],
        note: report['note']
      )

      authorize @assessment
      @assessment.save!
    end

    render json: { status: :created, message: "Assessments created" }
  end

  # GET /assessments/new
  def new
    @assessment_for = current_user.report(params[:team_member_bamboo_id])
    @assessment_round = @open_assessment_rounds.find(params[:assessment_round_id])

    @assessment = current_user.assessments.new(
      team_member_bamboo_id: params[:team_member_bamboo_id],
      assessment_round_id: @assessment_round.id
    )
    authorize @assessment
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = current_user.assessments.new(assessment_params)

    authorize @assessment

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to table_view_assessment_round_assessments_path(assessment_round: @assessment.assessment_round), notice: 'Assessment was successfully created.' }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { redirect_to new_assessment_path }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_assessment
    @assessment = Assessment.find(params[:id])
  end

  def assessment_params
    params.require(:assessment).permit(:motivation, :team_member_bamboo_id, :score_performance, :score_potential, :assessment_round_id, :note)
  end

  def bamboo_client
    @bamboo_client ||= Bamboo.new
  end

  def set_assessment_round
    @assessment_round = @open_assessment_rounds.find(params[:assessment_round_id])
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = 'Could not find an assessment round with that id'
    redirect_to root_path
  end
end

app/helpers/assessment_helper.rb
# frozen_string_literal: true

module AssessmentHelper
  def given_by(value, bamboo_id)
    user = User.find_by(id: value)
    user_on_bamboo = bamboo_client.find_team_member_by_id(user.bamboo_id.to_s)
    name = user_on_bamboo['fullName1']
    name += ' (self assessment)' if user.bamboo_id == bamboo_id
    name += ' (you)' if current_user == user
    name
  end

  def score(assessment)
    "#{assessment.score_potential} - #{assessment.score_performance}"
  end

  def last_assessment_at(bamboo_id, assessments)
    for_team_member = assessments.where(team_member_bamboo_id: bamboo_id).order(created_at: :desc).limit(1)
    return 'never assessed' if for_team_member.empty?

    "last assessed at #{for_team_member.first.created_at.to_formatted_s(:gitlab_iso)}"
  end

  def has_direct_reports?(bamboo_id)
    bamboo_client.direct_reports(bamboo_id).any?
  end

  def reports_for_title(reports_for)
    return "Your reports" if current_user.bamboo_id == reports_for['id']

    "Reports for #{reports_for['fullName1']}"
  end

  private

  def bamboo_client
    Bamboo.new
  end
end

app/views/assessments/_form.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <%= simple_form_for [assessment.assessment_round, assessment] do |f| %>
      <% assessment.errors.full_messages.each do |msg| %>
        <%= li= msg %>
      <% end %>

      <%= f.input :score_potential, collection: Assessment::POTENTIAL_VALUES.map{|value| [value.capitalize, value]} %>
      <%= f.input :score_performance, collection: Assessment::PERFORMANCE_VALUES.map{|value| [value.capitalize, value]} %>
      <%= f.input :note %>
      <%= f.input :team_member_bamboo_id, :as => :hidden %>
      <%= f.input :assessment_round_id, :as => :hidden %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/assessments/box_review.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <h3>Review Assessments for <%= @assessment_round.department %></h3>
    Team members can change box by grabbing them and droppping them on the correct box.
    Considering the round is in review stage, only the PBP can do this now.
  </div>
</div>

<div class='row'>
  <div class='col-sm-12'>
    <div id='assessment-box'
      data-bamboo-id='<%= current_user.bamboo_id.to_s %>'
      data-reports='<%= @reports.to_json %>'
      data-assessments='<%= @assessments.to_json %>'
      data-assessment-round='<%= @assessment_round.to_json %>'
      data-excluded=<%= @excluded_team_members %>>
    </div>
  </div>
</div>

app/views/assessments/edit.html.erb
<h1>Editing Assessment</h1>

<%= render 'form', assessment: @assessment %>

<%= link_to 'Show', @assessment %> |
<%= link_to 'Back', assessments_path %>

app/views/assessments/index.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <h3><%= @assessment_round.department || @assessment_round.division %></h3>
    You can assess a team member by grabbing them and droppping them on the correct box.
    If you prefer to assess each team member individually, you can go to
    the <%= link_to 'table view mode', table_view_assessment_round_assessments_path(@assessment_round) %>.
  </div>
</div>

<div class='row'>
  <div class='col-sm-12'>
    <div id='assessment-box'
      data-is-people-business-partner='<%= current_user.people_business_partner? %>'
      data-bamboo-id='<%= current_user.bamboo_id.to_s %>'
      data-reports='<%= @reports.to_json %>'
      data-assessments='<%= @assessments.to_json %>'
      data-assessment-round='<%= @assessment_round.to_json %>'>
    </div>
  </div>
</div>

app/views/assessments/new.html.erb
<h1>Add a new assessment for <%= @assessment_for['fullName1'] %></h1>

<%= render 'form', assessment: @assessment %>

app/views/assessments/table_view.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <h3><%= @assessment_round.department || @assessment_round.division %></h3>

    You can assess each team member individually by clicking the Assess link in their row.
    If you prefer the box view where you get all the selected team members, you can use
    the <%= link_to 'box view mode', assessment_round_assessments_path(@assessment_round) %>.
  </div>
</div>

<div class='row'>
  <div class='col-sm-12'>
    <table class='table table-bordered'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Add Assessment</th>
          <th>View all assessments</th>
        </tr>
      </thead>

      <tbody>
        <% @reports.each do |report| %>
          <tr>
            <td><%= report['fullName1'] %></td>
            <td>
              <%= link_to('Assess', new_assessment_round_assessment_path(@assessment_round.id, team_member_bamboo_id: report['id'])) %>
              <em>(<%= last_assessment_at(report['id'], @assessments) %>)</em>
            </td>
            <td>
              <%= link_to('History', user_assessments_path(team_member_bamboo_id: report['id'])) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>