config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :total_rewards, only: :index do
      collection do
        get 'download'
      end
    end

    resources :users do
      member do
        get 'impersonate'
      end
    end
    resources :assessment_rounds

    root to: "users#index"
  end

  resources :user_assessments, only: [:index]
  resources :assessment_rounds, only: [:new, :create, :show, :edit, :update] do
    resources :assessments, only: [:index, :new, :create] do
      collection do
        get 'table_view'
        get 'box_review'
        post 'update_box_view'
      end
    end

    member do
      get 'closed_view'
      get 'review'
      get 'download'
      post 'toggle_review_state'
      post 'close'
      post 'sync'
    end
  end

  devise_for :users, controllers: {
    confirmations: 'confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'
  get '/about', to: 'home#about'
  get '/dashboard', to: 'dashboard#index'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index
    @assessment_rounds = AssessmentRound.where(department: current_user.departments).or(AssessmentRound.where(division: current_user.divisions))
    authorize current_user, policy_class: DashboardPolicy
  end
end

app/views/dashboard/index.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <h4>
      Your Dashboard
      <%= link_to 'Start new Round', new_assessment_round_path, class: 'btn btn-success btn-md gl-button float-right' %>
    </h4>
  </div>
</div>

<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Active Rounds</a>
    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Synced Rounds</a>
    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Departments</a>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
    <div class='row'>

      <% if @assessment_rounds.not_synced.empty? %>
        <div class='col-sm-12'>
          <div class='card card-body'>
            There are no active assessment rounds.
          </div>
        </div>
      <% end %>

      <% @assessment_rounds.not_synced.each do |assessment_round| %>
        <div class="col-sm-4 mb-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">
                <%= assessment_round.department || assessment_round.division %>
              </h5>
              <p class="card-text">
                <div><b>State: </b><%= assessment_round.state %></div>
                <div><b>Start Date: </b><%= assessment_round.start_date %></div>
                <div><b>Due Date: </b><%= assessment_round.due_date %></div>
                <div><b>Percentage Complete: </b><%= assessment_round.percentage_complete %>%</div>
                <div><b>Started by:</b><%= assessment_round.user.email %></div>
              </p>
              <%= link_to 'Details', assessment_round_path(assessment_round), class: 'btn btn-info btn-md gl-button'%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
    <% if @assessment_rounds.closed_and_synced.empty? %>
      <div class='row'>
        <div class='col-sm-12'>
          <div class='card card-body'>
            You have no closed rounds yet.
          </div>
        </div>
      </div>
    <% else %>
      <div class="card">
      <div class="card-body">
        <h5 class="card-title">Passed Assessment Rounds</h5>
        <p class="card-text">
          <ul>
            <% @assessment_rounds.closed_and_synced.each do |assessment_round| %>
              <li>
                <%= assessment_round.department %>
                <%= link_to 'Summary', assessment_round_path(assessment_round) %>
              </li>
            <% end %>
          </ul>
        </p>
      </div>
    </div>
    <% end %>
  </div>

  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Your Departments</h5>
        <p class="card-text">
          <ul>
            <% current_user.departments.each do |department| %>
              <li>
                <%= department %>
                <% if @assessment_rounds.non_closed.for_department(department).none? %>
                  <%= link_to 'Start', new_assessment_round_path(department: department)  %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </p>
      </div>
    </div>
  </div>
</div>