config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :total_rewards, only: :index do
      collection do
        get 'download'
      end
    end

    resources :users do
      member do
        get 'impersonate'
      end
    end
    resources :assessment_rounds

    root to: "users#index"
  end

  resources :user_assessments, only: [:index]
  resources :assessment_rounds, only: [:new, :create, :show, :edit, :update] do
    resources :assessments, only: [:index, :new, :create] do
      collection do
        get 'table_view'
        get 'box_review'
        post 'update_box_view'
      end
    end

    member do
      get 'closed_view'
      get 'review'
      get 'download'
      post 'toggle_review_state'
      post 'close'
      post 'sync'
    end
  end

  devise_for :users, controllers: {
    confirmations: 'confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'
  get '/about', to: 'home#about'
  get '/dashboard', to: 'dashboard#index'
end

app/models/assessment_round.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: assessment_rounds
#
#  id                        :bigint           not null, primary key
#  cut_off                   :date
#  department                :string
#  division                  :string
#  due_date                  :date
#  load_previous_assessments :boolean          default(FALSE)
#  promotion_planning        :boolean          default(FALSE)
#  start_date                :date
#  state                     :integer          default("open")
#  succession_planning       :boolean          default(FALSE)
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  functional_lead_id        :integer
#  user_id                   :bigint           not null
#
# Indexes
#
#  index_assessment_rounds_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class AssessmentRound < ApplicationRecord
  belongs_to :user
  has_many :assessments, dependent: :destroy

  validates :due_date, :start_date, presence: true
  validate :only_one_open_per_department, :due_date_after_start_date, :start_date_is_not_in_the_past, on: :create
  validate :department_or_division_is_present, on: :create

  STATUSES = [:open, :in_review, :closed, :synced].freeze
  OPEN_STATUSES = [:open, :in_review].freeze
  CLOSED_STATUSES = [:closed, :synced].freeze
  EDITABLE_STATUSES = [:open, :in_review, :closed].freeze

  enum state: STATUSES

  scope :non_closed, -> { where(state: OPEN_STATUSES) }
  scope :closed_and_synced, -> { where(state: CLOSED_STATUSES) }
  scope :not_synced, -> { where.not(state: :synced) }
  scope :for_department, ->(department) { where('department = ?', department) }
  scope :for_division, ->(division) { where('division = ?', division) }

  before_create :set_functional_lead
  after_create :load_assessments, if: :load_previous_assessments?

  def ongoing?
    Date.current >= start_date && open?
  end

  def all_team_members_assessed?
    percentage_complete === 100.0
  end

  def assessed_team_members
    team_members = assessments.pluck(:team_member_bamboo_id).uniq.map do |id|
      bamboo_client.find_team_member_by_id(id)
    end.compact
    team_members.sort_by { |team_member| team_member['fullName1'] }
  end

  def percentage_complete
    all_assessment_ids = assessments.pluck(:team_member_bamboo_id).map(&:to_s).uniq
    all_eligibile_team_member_ids = eligible_team_members.pluck('id')
    (all_assessment_ids.size.to_f / (all_eligibile_team_member_ids.size - 1) * 100).round
  end

  def people_managers
    team_member_ids = bamboo_client.find_team_members_by_department(department).pluck('id') if department
    team_member_ids ||= bamboo_client.find_team_members_by_division(division).pluck('id') if division
    team_member_ids.each_with_object([]) do |id, array|
      array << bamboo_client.find_team_member_by_id(id) if bamboo_client.direct_reports(id).any?
    end
  end

  def move_to_review!
    return unless open?

    self.state = :in_review
    save!
  end

  def close!
    return unless in_review?

    self.state = :closed
    save!
  end

  def sync_to_bamboo!
    latest_confirmed_assessments = Assessment.most_recent_in_round(id).confirmed
    if ENV['SYNC_TO_BAMBOO']
      latest_confirmed_assessments.each do |assessment|
        bamboo_client.add_rating_details(
          assessment.team_member_bamboo_id,
          assessment.score_performance.capitalize,
          "#{assessment.score_potential.capitalize} Potential"
        )
      end
    end

    latest_confirmed_assessments.update(synced_at: DateTime.now)
    self.state = :synced
    save!
  end

  def generate_csv
    reports = eligible_team_members
    latest_assessments = Assessment.most_recent_in_round(id)
    CSV.generate(headers: true) do |csv|
      headers = %w[bamboo_id name department manager score_performance score_potential]
      if succession_planning || promotion_planning
        headers << 'emergency_contact'
        headers << 'time_frame'
        headers << 'time_frame_promotion'
      end
      csv << headers

      latest_assessments.each do |assessment|
        assessment_for = reports.find { |report| report['id'] == assessment.team_member_bamboo_id.to_s }
        # Could be someone was assessed but is no longer active
        next unless assessment_for

        manager = bamboo_client.find_team_member_by_id(assessment_for['supervisorEId'])
        row_data = [assessment.team_member_bamboo_id, assessment_for['fullName1'], assessment_for['department'], manager['fullName1'], assessment.score_performance, assessment.score_potential]
        if succession_planning || promotion_planning
          row_data << assessment.emergency_contact
          row_data << assessment.time_frame
          row_data << assessment.time_frame_promotion
        end

        csv << row_data
      end
    end
  end

  def total_rewards_data
    reports = eligible_team_members
    latest_assessments = Assessment.most_recent_in_round(id)

    latest_assessments.each_with_object([]) do |assessment, data|
      assessment_for = reports.find { |report| report['id'] == assessment.team_member_bamboo_id.to_s }
      next unless assessment_for

      data << [assessment_for['employeeNumber'], assessment_for['fullName1'], assessment.score_performance]
    end
  end

  def set_functional_lead
    return if functional_lead_id # it's already set
    return unless functional_lead

    self.functional_lead_id = functional_lead['id']
  end

  def eligible_team_members
    team_members = bamboo_client.find_team_members_by_department(department) if department
    team_members ||= bamboo_client.find_team_members_by_division(division) if division
    team_members.select! { |team_member| Date.parse(team_member['hireDate']).before?(cut_off) } if cut_off
    team_members
  end

  private

  def functional_lead
    possible_functional_leads = eligible_team_members.select do |tm|
      manager = eligible_team_members.find { |man| man['id'] === tm['supervisorEId'] }
      manager.nil?
    end

    Raven.capture_exception("Can't determine the functional lead correctly for assessment round #{id}") if possible_functional_leads.size > 1
    possible_functional_leads.first
  end

  def only_one_open_per_department
    errors.add(:department, "There can only be one open round/department.") if AssessmentRound.non_closed.where(department: department).exists? && department
  end

  def due_date_after_start_date
    errors.add(:due_date, "Due date needs to be after the start date.") if due_date <= start_date
  end

  def start_date_is_not_in_the_past
    errors.add(:start_date, "Start date can not be in the past.") if start_date < Date.today
  end

  def department_or_division_is_present
    errors.add(:department, 'No department or division is present') if division.nil? && department.nil?
  end

  def load_assessments
    round = AssessmentRound.where.not(id: id).where(department: department).order(created_at: :desc).first if department
    round ||= AssessmentRound.where.not(id: id).where(division: division).order(created_at: :desc).first if division

    round.assessments.each do |assessment|
      dup_assessment = assessment.dup
      dup_assessment.given_by = round.user.id
      dup_assessment.assessment_round = self
      dup_assessment.save
    end
  end
end

app/controllers/admin/assessment_rounds_controller.rb
# frozen_string_literal: true

module Admin
  class AssessmentRoundsController < Admin::ApplicationController
  end
end

app/controllers/assessment_rounds_controller.rb
# frozen_string_literal: true

class AssessmentRoundsController < ApplicationController
  before_action :set_assessment_round, only: [:show, :toggle_review_state, :review, :close, :sync, :download, :edit, :update, :closed_view]
  before_action :set_open_assessment_rounds, only: [:new]

  def closed_view
    @reports, @assessments = AssessmentPolicy::Scope.new(current_user, Assessment).resolve_for_round(@assessment_round)
    @reports.each { |report| report['fullName1'] = Faker::Name.name } if params[:demo] || ENV['DEMO_DATA']

    authorize @assessment_round
  end

  def new
    @assessment_round = current_user.assessment_rounds.new(department: params.dig(:department))
    @valid_departments = current_user.departments - @open_assessment_rounds.pluck(:department)
    authorize @assessment_round

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @assessment_round = current_user.assessment_rounds.new(assessment_round_params)
    authorize @assessment_round

    if @assessment_round.save
      redirect_to assessment_round_path(@assessment_round), notice: 'Assessment Round was successfully created.'
    else
      render :new, error: 'Something went wrong'
    end
  end

  def show
    authorize @assessment_round

    @all_team_members_assessed = @assessment_round.all_team_members_assessed?
    @people_managers = @assessment_round.people_managers
  end

  def edit
    authorize @assessment_round
  end

  def update
    authorize @assessment_round

    if @assessment_round.update(assessment_round_update_params)
      redirect_to assessment_round_path(@assessment_round), notice: 'Assessment Round was successfully updated.'
    else
      render :new, error: 'Something went wrong'
    end
  end

  def toggle_review_state
    authorize @assessment_round

    @assessment_round.move_to_review!
    redirect_to assessment_round_path(@assessment_round)
  end

  def review
    authorize @assessment_round
    redirect_to assessment_round_path(@assessment_round), notice: 'The assessment round is not in review state' unless @assessment_round.in_review?

    @assessed_team_members = @assessment_round.assessed_team_members
  end

  def close
    authorize @assessment_round

    unless @assessment_round.in_review?
      flash[:notice] = 'The assessment should be reviewed first'
      redirect_to assessment_round_path(@assessment_round)
      return
    end

    Assessment.most_recent_in_round(@assessment_round).update(confirmed_at: DateTime.current)

    @assessment_round.close!
    redirect_to assessment_round_path(@assessment_round)
  end

  def sync
    authorize @assessment_round

    unless @assessment_round.closed?
      flash[:notice] = 'This assessment round is not closed. Please close the assessment round first.'
      redirect_to assessment_round_path(@assessment_round)
      return
    end

    flash[:notice] = if @assessment_round.sync_to_bamboo!
                       'Successfully synced to BambooHR.'
                     else
                       flash[:notice] = 'There was a problem syncing the data to BambooHR. Try again or contact People Ops Engineering.'
                     end

    redirect_to assessment_round_path(@assessment_round)
  end

  def download
    authorize @assessment_round
    file_data = @assessment_round.generate_csv

    respond_to do |format|
      format.csv { send_data file_data, filename: "assessments-#{Date.today}.csv" }
    end
  end

  private

  def assessment_round_params
    params.require(:assessment_round).permit(:department, :due_date, :start_date, :promotion_planning, :succession_planning, :cut_off, :load_previous_assessments)
  end

  def assessment_round_update_params
    params.require(:assessment_round).permit(:due_date, :start_date, :promotion_planning, :succession_planning, :cut_off, :state)
  end

  def set_assessment_round
    @assessment_round = AssessmentRound.where(department: current_user.departments).or(AssessmentRound.where(division: current_user.divisions)).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = 'Can not find this Assessment round'
    redirect_to root_path
  end
end

app/helpers/assessment_round_helper.rb
# frozen_string_literal: true

module AssessmentRoundHelper
end

app/views/assessment_rounds/_timeline.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <ol class="dg_progress-tabs">
      <li class="highlight">Created</li>
      <li class="highlight <%= 'future' unless assessment_round.ongoing? || assessment_round.in_review? || assessment_round.closed? || assessment_round.synced? %>">Open for Assessments</li>
      <li class="highlight <%= 'future' unless assessment_round.in_review? || assessment_round.closed? || assessment_round.synced? %>">In Review</li>
      <li class="highlight <%= 'future' unless assessment_round.closed? || assessment_round.synced? %>">Confirmed</li>
      <li class="highlight <%= 'future' unless assessment_round.synced? %>">Sync to BambooHR</li>
    </ol>
  </div>
</div>

app/views/assessment_rounds/closed_view.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <h3><%= @assessment_round.department || @assessment_round.division %></h3>
    Read-only as it has been synced already to BambooHR.
  </div>
</div>

<div class='row'>
  <div class='col-sm-12'>
    <div id='assessment-box'
      data-is-people-business-partner='<%= current_user.people_business_partner? %>'
      data-bamboo-id='<%= current_user.bamboo_id.to_s %>'
      data-reports='<%= @reports.to_json %>'
      data-assessments='<%= @assessments.to_json %>'
      data-assessment-round='<%= @assessment_round.to_json %>'>
    </div>
  </div>
</div>

app/views/assessment_rounds/edit.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <%= simple_form_for @assessment_round do |f| %>
      <% @assessment_round.errors.full_messages.each do |msg| %>
        <%= li= msg %>
      <% end %>

      <%= f.input :start_date, as: :date, html5: true %>
      <%= f.input :due_date, as: :date, html5: true %>
      <%= f.input :promotion_planning, label: 'Enable Promotion Planning', hint: 'When you check this, you add the option to do promotion planning in the box view. Managers will be able to add a readiness time frame.' %>
      <%= f.input :succession_planning, label: 'Enable Succession Planning', hint: 'When you check this, you add the option to do succession planning in the box view. Managers will be able to add emergency contact and a readiness time frame.' %>
      <%= f.input :cut_off, as: :date, html5: true, label: 'Cut off date', hint: 'This is only needed if you want to exclude team members with a hire date after the cut off date.' %>
      <%= f.input :state, collection: AssessmentRound::EDITABLE_STATUSES.map {|value| [value.capitalize, value]} %>

      <%= f.button :submit, class: 'btn btn-success btn-md gl-button' %>
    <% end %>
  </div>
</div>

app/views/assessment_rounds/new.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <%= simple_form_for @assessment_round do |f| %>
      <% @assessment_round.errors.full_messages.each do |msg| %>
        <%= li= msg %>
      <% end %>

      <%= f.input :department, collection: @valid_departments %>
      <%= f.input :start_date, as: :date, html5: true %>
      <%= f.input :due_date, as: :date, html5: true %>
      <%= f.input :promotion_planning, label: 'Enable Promotion Planning', hint: 'When you check this, you add the option to do promotion planning in the box view. Managers will be able to add a readiness time frame.' %>
      <%= f.input :succession_planning, label: 'Enable Succession Planning', hint: 'When you check this, you add the option to do succession planning in the box view. Managers will be able to add emergency contact and a readiness time frame.' %>
      <%= f.input :cut_off, as: :date, html5: true, label: 'Cut off date', hint: 'This is only needed if you want to exclude team members with a hire date after the cut off date.' %>

      <%= f.input :load_previous_assessments, label: 'Load Assessments from Previous Round', hint: 'When you check this, we copy the assessments from last round into this assessment round. This will only be done if we can find a matching previous round.' %>

      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/assessment_rounds/review.html.erb
<div class='row'>
  <div class='col-sm-12'>
    Please select the team members you want to exclude from the review. Excluding means that we won't show them in the box view.

    <br />

    Team members with assessments:
    <%= form_with(url: box_review_assessment_round_assessments_path(@assessment_round), method: :get, local: true) do %>
      <% @assessed_team_members.each do |team_member| %>
        <p><%= check_box_tag 'excluded_team_members[]',  team_member['id'] %> <%= team_member['fullName1'] %></p>
      <% end %>
      <%= submit_tag "Start Review", class: 'btn btn-success btn-md gl-button' %>
    <% end %>
  </div>
</div>

app/views/assessment_rounds/show.html.erb
<%= render 'timeline', assessment_round: @assessment_round %>

<div class='row'>
  <div class='col-sm-10'>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Assessment round for <%= @assessment_round.department || @assessment_round.division %></h5>
        <p class="card-text">
          <div class='row'>
            <div class='col-sm-5'>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-week" viewBox="0 0 16 16">
                <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
                <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
              </svg>
              <%= @assessment_round.start_date %> -
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-week" viewBox="0 0 16 16">
                <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
                <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
              </svg>
              <%= @assessment_round.due_date %>
            </div>
            <div class='col-sm-5'>
              <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: <%= @assessment_round.percentage_complete %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><%= @assessment_round.percentage_complete %>%</div>
              </div>
              <div>Headcount: <%= @assessment_round.eligible_team_members.size %></div>
            </div>
          </div>
        </p>
      </div>
    </div>
  </div>

  <div class='col-sm-2'>
    <b>Actions:</b>
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to 'Edit Round', edit_assessment_round_path(@assessment_round), class: 'nav-link assessment-round-vertical-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Export Data', download_assessment_round_path(@assessment_round, format: :csv), class: 'nav-link assessment-round-vertical-link' %>
      </li>

      <% if @assessment_round.ongoing? %>
        <li class="nav-item">
          <%= link_to 'Move to Review', toggle_review_state_assessment_round_path(@assessment_round), class: 'nav-link assessment-round-vertical-link', method: :post, data: {confirm:"This will move the assessment round in the review stage. In this stage only People Business Partners can make changes to the assessments and guide the callibration meetings. Are you sure you want to move to the review stage?"} %>
        </li>
      <% end %>

      <% unless @assessment_round.synced? %>
        <li class="nav-item">
          <%= link_to 'Open box view', assessment_round_assessments_path(@assessment_round), class: 'nav-link assessment-round-vertical-link' %>
        </li>
      <% end %>

      <% if @assessment_round.in_review? %>
        <li class="nav-item">
          <%= link_to 'Open review mode', review_assessment_round_path(@assessment_round), class: 'nav-link assessment-round-vertical-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Confirm review', close_assessment_round_path(@assessment_round), class: 'nav-link assessment-round-vertical-link', method: :post, data: {confirm:"This will close the assessment round and confirm the latest assessment. Are you sure you want to do this?"} %>
        </li>
      <% end %>

      <% if @assessment_round.closed? %>
        <li class="nav-item">
          <%= link_to 'Sync to BambooHR', sync_assessment_round_path(@assessment_round), class: 'nav-link assessment-round-vertical-link', method: :post, data: {confirm:"This will move the assessment round in the review stage. In this stage only People Business Partners can make changes to the assessments and guide the callibration meetings. Are you sure you want to move to sync the data to BambooHR?"} %>
        </li>
      <% end %>

      <% if @assessment_round.synced? %>
        <li class="nav-item">
          <%= link_to 'Open box view (read only)', closed_view_assessment_round_path(@assessment_round), class: 'nav-link assessment-round-vertical-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <% if Date.current <= @assessment_round.start_date %>
      This assessment round is not open yet. You can already send out emails to the
      managers involved in this round. Here is a list of all the people managers:

      <ul>
      <% @people_managers.each do |people_manager| %>
        <li><%= people_manager['fullName1'] %> - <%= people_manager['workEmail'] %></li>
      <% end %>
    </ul>
    <% end %>

    <% if @assessment_round.ongoing? %>
      This round is currently open and managers are able to assess their team members.
      If you want to move the round to the next stage, you can click the `Move to Review`
      link on this page. In review mode, managers will no longer be able to make assessments.
    <% end %>

    <% if @assessment_round.in_review? %>
      Please schedule a meeting with the following people managers:
      <ul>
        <% @people_managers.each do |people_manager| %>
          <li><%= people_manager['fullName1'] %> - <%= people_manager['workEmail'] %></li>
        <% end %>
      </ul>

      You can use the <%= link_to 'review mode', review_assessment_round_path(@assessment_round) %>
      during your meeting to discuss the assessments with the managers.

      <br />
      <br />

      When you're done with the review, please <%= link_to 'confirm', close_assessment_round_path(@assessment_round), method: :post, data: {confirm:"This will close the assessment round and confirm the latest assessment. Are you sure you want to do this?"} %>
       it. Confirm means that we will finalize the latest
      assessments for everyone. Those are the values that will be synced to BambooHR later on.
    <% end %>

    <% if @assessment_round.closed? %>
      This round is closed. The only step left is to <%= link_to 'sync the data to BambooHR.', sync_assessment_round_path(@assessment_round), method: :post, data: {confirm:"This will move the assessment round in the review stage. In this stage only People Business Partners can make changes to the assessments and guide the callibration meetings. Are you sure you want to move to sync the data to BambooHR?"} %>
      Once synced the data can not be
      edited anymore. Make sure to double check the assessments.
    <% end %>

    <% if @assessment_round.synced? %>
      This round is closed and synced to BambooHR. If edits need to be made, they also need to
      be made on BambooHR. Contact someone from Total Rewards and People Engineering to help
      you with this step.
    <% end %>
  </div>
</div>