config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :total_rewards, only: :index do
      collection do
        get 'download'
      end
    end

    resources :users do
      member do
        get 'impersonate'
      end
    end
    resources :assessment_rounds

    root to: "users#index"
  end

  resources :user_assessments, only: [:index]
  resources :assessment_rounds, only: [:new, :create, :show, :edit, :update] do
    resources :assessments, only: [:index, :new, :create] do
      collection do
        get 'table_view'
        get 'box_review'
        post 'update_box_view'
      end
    end

    member do
      get 'closed_view'
      get 'review'
      get 'download'
      post 'toggle_review_state'
      post 'close'
      post 'sync'
    end
  end

  devise_for :users, controllers: {
    confirmations: 'confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'
  get '/about', to: 'home#about'
  get '/dashboard', to: 'dashboard#index'
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand mb-0 h1 text-light" href='/'>GitLab Assessments</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    </ul>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item dropdown my-2 my-lg-0">
          <a class="text-light nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'About', about_path, class: 'dropdown-item' %>
            <% if current_user.people_business_partner? %>
              <%= link_to 'Dashboard', dashboard_path, class: 'dropdown-item' %>
            <% end %>

            <% if current_user.admin? %>
              <%= link_to 'Admin', admin_root_path, class: 'dropdown-item' %>
            <% end %>

            <% if current_user.total_rewards? %>
              <%= link_to 'Total Rewards', admin_total_rewards_path, class: 'dropdown-item' %>
            <% end %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item') %>
          </div>
        </li>
      </ul>
    <% else %>
      <li class='nav-item'>
          <%= link_to('Login', new_user_session_path, class: 'nav-link text-light') %>
        </li>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoxAssessment</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "9 Box Assessments" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'assessment' %>
  </head>

  <body>
      <%= render 'layouts/navigation' %>
      <%= render 'shared/banners' %>
    <main role="main" class='container'>
      <div class='ie-main'>
        <%= content_for?(:content) ? yield(:content) : yield %>
      </div>

    </main>
  </body>
</html>